// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	//"database/sql"
)

type Xmld struct {
	Name   string         `json:"name"`
	Config []byte   `json:"config"`
}
