// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"
	//"database/sql"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (Xmld, error)
	Get(ctx context.Context, name string) (Xmld, error)
}

var _ Querier = (*Queries)(nil)
